---
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - { role: "geerlingguy.security", tags: [ "security" ] }
    - { role: "geerlingguy.pip", tags: [ "pip" ] }
    - { role: "geerlingguy.docker", tags: [ "docker" ] }
