- name: Bootstrap a raspberry pi
  hosts: pis
  become: yes
  gather_facts: no

  tasks:
    - block:
      - name: Check connection
        command:
          cmd: 'whoami'
        changed_when: False

      - name: Install some packages
        apt:
          state: present
          name: [ 'sudo', 'git', 'vim' ]

      - name: Set root password
        user:
          name: root
          password: "{{ password | password_hash('sha512') }}"

      - name: Make "{{ username }}" user
        user:
          name: "{{ username }}"
          password: "{{ password | password_hash('sha512') }}"
          append: yes
          groups:
            - sudo
            - systemd-journal
            - dialout
            - gpio
            - spi
            - i2c
          shell: /bin/bash

      - name: Allow sudoers to sudo without password
        lineinfile:
          path: /etc/sudoers
          state: present
          regex: "^%sudo"
          line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
          validate: /usr/sbin/visudo -cf %s

      - name: Disable requiretty in /etc/sudoers
        replace:
          dest: "/etc/sudoers"
          regexp: '^Defaults\s+requiretty$'
          replace: "# Defaults    requiretty"
          validate: /usr/sbin/visudo -cf %s

      - name: Change hostname
        hostname:
          name: "{{ inventory_hostname }}"

      - name: Reboot machine to let hostname change take effect
        command:
          cmd: 'reboot'
        poll: 0
        async: 0
        ignore_errors: True
      delegate_to: pinky.local
      vars:
        ansible_user: pi
        ansible_password: raspberry
        ansible_become_pass: "{{ ansible_password }}"

    - name: Switch to me
      set_fact:
        ansible_user: "{{ username }}"
        ansible_pass: "{{ password }}"
        ansible_ssh_pass: "{{ password }}"

    - name: Reset ssh connection
      meta: reset_connection

    - name: Wait for machine to come back up
      wait_for_connection:
        delay: 15
        timeout: 240

    - name: Delete pi user
      user:
        name: pi
        state: absent
        remove: yes

    - name: Disable root user
      user:
        name: root
        password: "!"

    - name: Update and upgrade
      apt:
        update_cache: yes
        upgrade: safe
        autoclean: yes
